### ISSUE TITLE
JUnit testování

### ISSUE THREAD

**Issue by DeznekCZ** [DeznekCZ/zswi_eeg_explorer_2015#10]
Zprovoznil jsem JUnit testvání, potřeboval jsem ověřit pár dat a tento nástroj mi to velice ušetřil. Pokud máte IDE Eclipse LUNA, měl by být JUnit instalován uvnitř a bez problému by měl jít projekt sestavit.

**Comment by seky739** [comment]
přidány další testy nyní 74% kódovaných funkcionalit pokryto .

**Comment by seky739** [comment]
nyní pokryto 85% funkcionalit
