### ISSUE TITLE
Editable Field Popis

### ISSUE THREAD

**Issue by seky739** [DeznekCZ/zswi_eeg_explorer_2015#11]
Ahoj takže koukal jsem na to co udělal zdeněk to EditableField šlo by to použít teda tak aby se to vypisovalo. Ale nějaký bližší popis protože po mém pokusu tam přidat další instanci mi to vypíše v názvu <vhdr_XXXXX> kde XXXX je název daného atributu headru . Rád bych teda pokud by šlo k tomu dopsat komentáře. Díky :)

**Comment by DeznekCZ** [comment]
Celé jsem to předělal, ale chybí ještě vyřešit, jakým způsobem se budou upravovat chanely

**Comment by DeznekCZ** [comment]
Momentálně opět funguje starší verze.

**Comment by seky739** [comment]
super
