### ISSUE TITLE
UI - problémy

### ISSUE THREAD

**Issue by DeznekCZ** [DeznekCZ/zswi_eeg_explorer_2015#13]
Dnes jsem při ladění UI narazil na problém. Při odstranění zázložky z editoru se vymažou všechna menu z ostatních záložek. Pokusím se s tím poprat, dám tomu maximálně 3 hodiny. Pokud se mi to nepodaří ošetřit, vrátím menu nad záložky.

**Comment by DeznekCZ** [comment]
Problém vyřešen, je to nyní paměťově náročnější, ale funkci splňuje, pokud zbyde čas, budu jej ještě ladit.

**Comment by seky739** [comment]
ok
