### ISSUE TITLE
Error while opening vhdr

### ISSUE THREAD

**Issue by seky739** [DeznekCZ/zswi_eeg_explorer_2015#14]
Hoj tak jsem našel takový menší problém při pokusu otevřít např : masarykovo004_20141124.vhdr  nebo masarykovo003_20141124.vhdr napíše file is not readable ale přitom tam všechno je a soubor je bez křížku. Zkus zdendo na to juknout nevím proč mi to nechce otevřít do editu .

**Comment by DeznekCZ** [comment]
Ten kříže právě neodhalí všechny chyby, je to tím, že načítání probíhá jiným způsobem. Ten křížek říká, že mu chybí *.vmrk a *.eeg soubory.

**Comment by DeznekCZ** [comment]
Chyba vzniká při parsování Channelů a výjimku vyhazuje převod řetězce na číslo. Pravděpodobně se musí užít Long.parseLong(String) namísto Integer.parseInt()

**Comment by seky739** [comment]
Opraveno na double +1:
