### ISSUE TITLE
Problém při testech ukládání

### ISSUE THREAD

**Issue by DeznekCZ** [DeznekCZ/zswi_eeg_explorer_2015#15]
Během testu uložitelnosti souboru vyskakovala výjimka, že utíka index.

ArrayOutOfBoundsException

Chyba není programová, ale vychází z vlastnosti metody new String().split(String, int), kde je nutné do předělujícího řetězce v případě dělení přes '.' (tečku) dodat symbol '\\'. Výsledné dělení vypadá takto:

String[] pole = ((String) hodnota).split("\\\\."); 

// přetypování není nutné pokud, jde pouze o to, že to musí být řetězec.

Chybu jsem opravil.

Použití je popsáno v Java dokumentaci knihovny String, ale velmi nešťastně.

**Comment by seky739** [comment]
vyřešeno
