### ISSUE TITLE
Refaktorizace architektury

### ISSUE THREAD

**Issue by DeznekCZ** [DeznekCZ/zswi_eeg_explorer_2015#16]
Díky špatné objektové analýze jsem vytvořil funkční ale dále nešiřitelný kód. Věřím, že dokončíme aplikaci včas, ale není zaručeno, že bude porovedena podle všech OOP a PMD konvencí.

**Comment by DeznekCZ** [comment]
V ukládání ve třídě RenameAndSave použij metody z FilesIO, protože teato třída by již neměla pracovat s instancemi File
Druhé doporučení, vytvoř místo konstruktoru statickou metodu

**Comment by seky739** [comment]
rád bych asi abychom tuto třídu úplně eliminovali aby se nám dělo vše ohledně file v balíku io

**Comment by seky739** [comment]
Změna názvu balíčků na celý název feditor ->> fileeditor

**Comment by seky739** [comment]
dialog -> dialogmanagement

**Comment by DeznekCZ** [comment]
Primární problémy odstraněny
