### ISSUE TITLE
Kopírování souborů

### ISSUE THREAD

**Issue by DeznekCZ** [DeznekCZ/zswi_eeg_explorer_2015#7]
Je nutné přepsat kopírovací funkci pro soubory VHDR, VMRK a EEG, nyní budu pokračovat ve zdokonalování UI a funkcionánální část nechávám na vás.

**Comment by seky739** [comment]
VHDR mám merging hotový

**Comment by DeznekCZ** [comment]
Šlo by to zakomponovat do již existujícího VMRK.java v cz.eeg.data.

**Comment by seky739** [comment]
šlo ale to potřebuju abys tu třídu okomentoval pořádně protože se v tom vůbec nevyznám :)

**Comment by seky739** [comment]
ještě mě napadlo ty ten VHDR ale otevíráš pro ten editor ale jak víš že zrovna tyhle chce spojit???

**Comment by DeznekCZ** [comment]
Mám v plánu vytvořit proměnnou SPOJOVANÝ_SOUBOR tím a tlačítka "Nastavit jako spojovaný" a "Spojit". Tahle varianta je pro editor a z prohlížeče to budu připojovat po jednom tím, že vezmu list, který je vybrán, jako když ty soubory otvírám, což bude položka menu, případně klávesová zkratka

**Comment by DeznekCZ** [comment]
Komentáře doplním
